// <auto-generated />
using System;
using LottoTM.Server.Api.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LottoTM.Server.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LottoTM.Server.Api.Entities.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DrawDate")
                        .HasColumnType("date");

                    b.Property<string>("LottoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DrawDate", "LottoType")
                        .IsUnique();

                    b.ToTable("Draws", (string)null);
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.DrawNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrawId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DrawId");

                    b.HasIndex("Number");

                    b.HasIndex("DrawId", "Position")
                        .IsUnique();

                    b.ToTable("DrawNumbers", null, t =>
                        {
                            t.HasCheckConstraint("CHK_DrawNumbers_Number", "[Number] >= 1 AND [Number] <= 49");

                            t.HasCheckConstraint("CHK_DrawNumbers_Position", "[Position] >= 1 AND [Position] <= 6");
                        });
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.TicketNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketId", "Position")
                        .IsUnique();

                    b.ToTable("TicketNumbers", null, t =>
                        {
                            t.HasCheckConstraint("CHK_TicketNumbers_Number", "[Number] >= 1 AND [Number] <= 49");

                            t.HasCheckConstraint("CHK_TicketNumbers_Position", "[Position] >= 1 AND [Position] <= 6");
                        });
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.Draw", b =>
                {
                    b.HasOne("LottoTM.Server.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedDraws")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.DrawNumber", b =>
                {
                    b.HasOne("LottoTM.Server.Api.Entities.Draw", "Draw")
                        .WithMany("Numbers")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draw");
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.Ticket", b =>
                {
                    b.HasOne("LottoTM.Server.Api.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.TicketNumber", b =>
                {
                    b.HasOne("LottoTM.Server.Api.Entities.Ticket", "Ticket")
                        .WithMany("Numbers")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.Draw", b =>
                {
                    b.Navigation("Numbers");
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.Ticket", b =>
                {
                    b.Navigation("Numbers");
                });

            modelBuilder.Entity("LottoTM.Server.Api.Entities.User", b =>
                {
                    b.Navigation("CreatedDraws");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
